version: "3.9"
include:
    - path: ./infra.yml

services:
    community:
        build:
            context: ./python
            dockerfile: services/community/Dockerfile
        container_name: community.rest
        ports:
            - "8010:8000"
        env_file:
            - .env
            - ./python/services/community/.env
        depends_on:
            - redis
            - mongodb
        restart: unless-stopped
        networks:
            - backend
